FROM python:3.10-slim-bookworm

WORKDIR /app

COPY requirements.txt .



RUN pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt

# Create necessary directories
RUN mkdir -p data vector_store

COPY src/ ./src/

ENV PYTHONPATH=/app
ENV DATABASE_URL="postgresql://creditrust:supersecret@db:5432/creditrust"

EXPOSE 8000

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
